server:
  port: 8081
spring:
#  application:
#    name: reverie-dianping
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/reverie_dp?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: tang20020504
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
        max-wait: 2000ms
    timeout: 3s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.whurs.entity # 别名扫描包
logging:
  level:
    com.whurs: debug
canal:
  destination: example # canal的集群名字，要与安装canal时设置的名称一致
  server: 127.0.0.1:11111 # canal服务地址